### PR TITLE
Add support for Sylius 1.8

### LINKED ISSUE #2: Add support for Sylius 1.8

### PR DESCRIPTION
**Pull request by DieterHolvoet**
WIP, fixes #2.

### CODE REVIEW

**Comment by DieterHolvoet** [comment]
@nedac-sorbo The tests are failing due to the `TOKEN` env variable being empty. Any way around this?

**Review by 4c0n — CHANGES_REQUESTED** [review]
Hoi @DieterHolvoet, thanks for your work on this plugin.

The CI should be testing the plugin on all supported Sylius versions. The policy is to support patch version it was developed on and up (with as goal to just support the latest patch version).
Hence the separated test application. In order to do that, the master branch of the test application repository should be branched to "1.7" first. Then apply the changes to the master branch and update the Travis configuration to include the new job.

**Comment by 4c0n** [comment]
> @nedac-sorbo The tests are failing due to the `TOKEN` env variable being empty. Any way around this?

Not sure what is going here, I would have to look into that, but currently don't have any time to do that.

**Comment by joenilson** [comment]
Hi it appears that do you need to update your auth token, may be [this link help you](https://blog.simplytestable.com/creating-and-using-a-github-oauth-token-with-travis-and-composer/) @4c0n.

I'm interested in this plugin too, if there is a way to help, i'll glad to hear.

**Comment by 4c0n** [comment]
@joenilson Thanks for your reponse. The token issue should be resolved soon.
What I would like is for this plugin to basically get rid of the test application, build/use the container images in github actions and install + test the plugin on several different versions of Sylius. However there are a few problems. Our company is currently using the (modified) bootstrap theme, but there is no official release there and it is not properly maintained. So I would like to fork that first and have a better/stable bootstrap theme available to test with.
By installing the plugin on a fresh Sylius standard instance the installation steps will also be tested.
Not sure exactly when I'll have time to work on all of that. But likely somewhere in 2021.

**Comment by xchopin** [comment]
Any updates on this?

**Comment by 4c0n** [comment]
Skipping 1.8 support in favor of supporting 1.9 which I'm currently working on.

**Pull request closed without merging**
